Paradise/Paradise/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Paradise/app/urls.py
from django.urls import path
from app.views import UserProfile



urlpatterns = [
    path('accounts/profile/', UserProfile.as_view(), name='profile'),
    
]

Paradise/users/urls.py
from django.contrib import admin
from .views import *
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .forms import PasswordResetForm
from . import views



urlpatterns = [
    path('', home, name='index'),
    path('index/', home, name='index'),
    path('login/' , auth_views.LoginView.as_view (template_name='login.html') , name="login_attempt"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    
    path('register/cpf/', CPFView.as_view(), name='cpf'),
    path('register/name-email/', NameEmailView.as_view(), name='name_email'),
    path('register/email-verification/', EmailVerificationView.as_view(), name='email_verification'),
    path('register/phone-number/', PhoneNumberView.as_view(), name='phone_number'),
    path('register/sms-verification/', SMSVerificationView.as_view(), name='sms_verification'),
    path('register/date-of-birth/', DateOfBirthView.as_view(), name='date_of_birth'),
    path('register/password/', PasswordView.as_view(), name='password'),
    path('register/complete/', RegistrationCompleteView.as_view(), name='registration_complete'),
    path('terms-of-service/', terms_of_service, name='terms_of_service'),
    
    path('token/' , token_send , name="token_send"),
    path('success/' , success , name='success'),
    path('verify/<auth_token>/' , verify , name="verify"),
    path('error/' , error_page , name="error"),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(
    form_class=PasswordResetForm,
    template_name='registration/password_reset_form.html',
    email_template_name='registration/password_reset_email.html',
    subject_template_name='registration/password_reset_subject.txt',
    extra_context={
        'protocol': 'http',
    }
), name='password_reset'),

    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(
    template_name='registration/password_reset_done.html'
), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html',
        success_url='/login/'
    ), name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
    template_name='registration/password_reset_complete.html'
), name='password_reset_complete'),

    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='registration/password_change_form.html',
        success_url='/password_change_done/'
    ), name='password_change'),

    # URL para confirmação de alteração de senha
    path('password_change_done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='registration/password_change_done.html',
    ), name='password_change_done'),

    path('terms-of-service/', views.terms_of_service, name='terms_of_service'),
    path('email-verification/', views.email_verification, name='email_verification'),
    path('send_otp/', views.sendOtp.as_view(), name='sendotp'),
    path('email/', views.email, name="email"),
    path('account/', views.account, name="account"),
    path('verification/<uidb64>/<token>/', views.verification, name='verification'),
]

Paradise/app/models.py
from django.db import models
from django.utils.timezone import now
from django.conf import settings
from django.urls import reverse


class PaymentMethod(models.Model):
    method_id = models.AutoField(primary_key=True)
    method_type = models.CharField(max_length=255, default='')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='payment_user', on_delete=models.PROTECT)

    def __str__(self):
        return str(self.method_id)


class Account(models.Model):
    payment = models.OneToOneField(PaymentMethod, on_delete=models.CASCADE)
    balance = models.FloatField(default=0.00)

    def __str__(self):
        return 'Account: %s' % self.payment.user.username

    def get_update_url(self):
        return reverse('account_transfer', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        # ensure that the database only stores 2 decimal places
        self.balance = round(self.balance, 2)
        super(Account, self).save(*args, **kwargs)


class Bank(models.Model):
    payment = models.OneToOneField(PaymentMethod, on_delete=models.CASCADE)
    owner_first_name = models.CharField(max_length=255, default=None)
    owner_last_name = models.CharField(max_length=255, default=None)
    routing_number = models.CharField(max_length=9, default=None)
    account_number = models.CharField(max_length=10, default=None)

    def __str__(self):
        return 'Bank: ****%s' % self.account_number[5:]

    def get_absolute_url(self):
        return reverse('bank_detail', kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('bank_update', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('bank_delete', kwargs={'pk': self.pk})

    class Meta:
        unique_together = ('routing_number', 'account_number')


Card_Type = (
    ('Credit', 'Credit Card'),
    ('Debit', 'Debit Card'),
)


class Card(models.Model):
    payment = models.OneToOneField(PaymentMethod, on_delete=models.DO_NOTHING)
    card_type = models.CharField(max_length=45, choices=Card_Type)
    card_number = models.CharField(max_length=16, default=None)
    owner_first_name = models.CharField(max_length=45)
    owner_last_name = models.CharField(max_length=45)
    security_code = models.CharField(max_length=3, default=None)
    expiration_date = models.DateField(default=None)

    def get_absolute_url(self):
        return reverse('card_detail', kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('card_update', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('card_delete', kwargs={'pk': self.pk})

    def __str__(self):
        return '%s Card: ************%s' % (self.card_type, self.card_number[12:])

    class Meta:
        unique_together = ('card_type', 'owner_first_name', 'owner_last_name',
                           'card_number', 'security_code', 'expiration_date')
        ordering = ['card_type', 'card_number']


Transaction_Type = (
    ('send', 'Send'),
    ('request', 'Request'),
    ('transfer', 'Transfer'),
)


Categories = (
    ('Bank', 'Bank Transfer'),
    ('Utilities', 'Bills & Utilities'),
    ('Transportation', 'Auto & Transport'),
    ('Groceries', 'Groceries'),
    ('Food', 'Food'),
    ('Shopping', 'Shopping'),
    ('Health', 'Healthcare'),
    ('Education', 'Education'),
    ('Travel', 'Travel'),
    ('Housing', 'Housing'),
    ('Entertainment', 'Entertainment'),
    ('Others', 'Others'),
)


class Transaction(models.Model):
    transaction_id = models.AutoField(primary_key=True)
    transaction_type = models.CharField(max_length=45, choices=Transaction_Type, default='')
    category = models.CharField(max_length=45, choices=Categories)
    amount = models.FloatField(default=0.00)
    description = models.CharField(max_length=200, default=False)
    create_date = models.DateTimeField(default=now, editable=False)
    is_complete = models.BooleanField(default=False)
    receiver = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='receiver', on_delete=models.PROTECT, default='')
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='creator', on_delete=models.PROTECT, default='')
    payment_method = models.ForeignKey(PaymentMethod, related_name='payment_method',
                                       on_delete=models.PROTECT, default='', null=True)

    def get_absolute_url(self):
        return reverse('staff_tran_detail', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('staff_tran_delete', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        # ensure that the database only stores 2 decimal places
        self.amount = round(self.amount, 2)
        super(Transaction, self).save(*args, **kwargs)

    def __str__(self):
        return str(self.transaction_id)

    class Meta:
        ordering = ['category']

Paradise/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.core.exceptions import ValidationError
from decimal import Decimal
from django.utils.translation import gettext_lazy as _
from django.conf import settings
import uuid
from django.utils import timezone
from django_countries.fields import CountryField

from .choices import COUNTRIES

class UserManager(BaseUserManager):
    def create_user(self, email, cpf, password=None, **extra_fields):
        if not email:
            raise ValueError('O usuário deve ter um endereço de email')
        if not cpf:
            raise ValueError('O usuário deve ter um CPF')

        email = self.normalize_email(email)
        user = self.model(email=email, cpf=cpf, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, cpf, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser deve ter is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser deve ter is_superuser=True.')

        return self.create_user(email, cpf, password, **extra_fields)

class User(AbstractUser):
    cpf = models.CharField(max_length=14, unique=True)
    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=15, unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    is_email_verified = models.BooleanField(default=False)
    is_phone_verified = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'cpf', 'phone_number']

    objects = UserManager()

    def __str__(self):
        return self.email

    def clean(self):
        super().clean()

        # Verifica se já existe um usuário com o mesmo CPF
        if User.objects.filter(cpf=self.cpf).exclude(pk=self.pk).exists():
            raise ValidationError({'cpf': _('Este CPF já está cadastrado. Por favor, insira outro CPF.')})

        # Verifica se já existe um usuário com o mesmo email
        if User.objects.filter(email=self.email).exclude(pk=self.pk).exists():
            raise ValidationError({'email': _('Este email já está cadastrado. Por favor, insira outro email.')})

    def save(self, *args, **kwargs):
        self.cpf = self.cpf.replace('.', '').replace('-', '')
        self.clean()
        super().save(*args, **kwargs)

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    birthday = models.DateField(null=True, blank=True)
    address = models.CharField(verbose_name="Address", max_length=100, null=True, blank=True)
    town = models.CharField(verbose_name="Town/City", max_length=100, null=True, blank=True)
    county = models.CharField(verbose_name="County", max_length=100, null=True, blank=True)
    post_code = models.CharField(verbose_name="Post Code", max_length=8, null=True, blank=True)
    country = CountryField(verbose_name="Country", null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    auth_token = models.UUIDField(default=uuid.uuid4, editable=False)
    is_verified = models.BooleanField(default=False)
    email_verified = models.BooleanField(default=False)
    two_step_active = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.user.email

class OtpToken(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="otps")
    otp_code = models.CharField(max_length=6)
    otp_created_at = models.DateTimeField(auto_now_add=True)
    otp_expires_at = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return f"OTP for {self.user.email} - Expires at {self.otp_expires_at}"

    @classmethod
    def check_otp(cls, user, otp_code):
        try:
            otp = cls.objects.get(user=user, otp_code=otp_code)
            if otp.otp_expires_at > timezone.now():
                return True
            else:
                return False
        except cls.DoesNotExist:
            return False

class UserToken(models.Model):
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=100, null=True, blank=True)
    two_step_code = models.CharField(max_length=6, null=True, blank=True)
    
    # used to change the object type
    is_email = models.BooleanField(default=False)
    is_password = models.BooleanField(default=False)
    is_sms = models.BooleanField(default=False)

    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.user}'

Paradise/users/templates/error.html
{% extends "base.html" %}

{% block title %}Error{% endblock title %}

{% block content %}
    <h2>Error</h2>
    <p>An error occurred. Please try again later or contact support.</p>
{% endblock content %}

Paradise/users/templates/home.html
{% load static %}

<!DOCTYPE html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Paradise</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <!--<link rel="shortcut icon" type="image/x-icon" href="../static/img/favicon.png"> -->
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/gijgo.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/slicknav.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">


    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>

<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
    <header>
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-xl-3 col-lg-2">
                            <div class="logo">
                                <a href="{% url 'login_attempt' %}">
                                    <img src="{% static 'img/logo.png' %}" alt="">
                                </a>
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-7">
                            <div class="main-menu  d-none d-lg-block">
                                <nav>
                                    <ul id="navigation">
                                        <li><a class="active" href="{% url 'login_attempt' %}">Home</a></li>
                                        {% if perms.app.add_transaction%}
                                            <li><a href="{% url 'login_attempt' %}">Activity</a></li>
                                        {% endif %}
                                        {% if perms.app.add_transaction %}
                                            <li><a href="{% url 'login_attempt' %}">Send & Request</a>
                                        {% endif %}
                                        {% if perms.app.add_account%}
                                            <li><a href="{% url 'login_attempt' %}">Wallet</a></li>
                                        {% endif %}
                                        {% if perms.app.change_profile %}
                                            <li><a href="{% url 'login_attempt' %}">User Profile</a></li>
                                        {% endif %}

                                        {% if perms.app.delete_transaction %}
                                            <li><a href="{% url 'login_attempt' %}">User List</a></li>
                                        {% endif %}
                                        {% if perms.app.delete_transaction %}
                                            <li><a href="{% url 'login_attempt' %}">Transactions</a></li>
                                        {% endif %}

                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                            <div class="Appointment">
                                <div>
                                    {% if user.is_authenticated %}
                                        <form id="logout-form" action="{% url 'logout' %}" method="post" style="display:none;">
                                            {% csrf_token %}
                                        </form>
                                        <div class="book_btn d-none d-lg-block">
                                             <a href="#" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Log Out</a>
                                        </div>
                                    {% else %}
                                        <div class="book_btn d-none d-lg-block"><a href="{% url 'login_attempt' %}">Login</a></div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- header-end -->

    <!-- slider_area_start -->
    <div class="slider_area">
        <div class="slider_active owl-carousel">
            <div class="single_slider  d-flex align-items-center slider_bg_1">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="slider_text ">
                                <h3> <span>PARADISE</span> </h3>
                                <p>nandao777 - nandao777</p>
                                {% if perms.app.add_account %}
                                    <a href="{% url 'login_attempt' %}" class="boxed-btn3">Check Wallet</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- slider_area_end -->

    <!-- service_area_start -->
    <div class="service_area">
        <div class="container p-0">
            <div class="row no-gutters">
                <div class="col-xl-4 col-md-4">
                    <div class="single_service">
                        <div class="icon">
                            <i class="flaticon-money"></i>
                        </div>
                        <h3>Send</h3>
                        <p>Send your money to your friend within a minute.</p>
                        {% if perms.app.add_transaction %}
                            <a href="{% url 'login_attempt' %}" class="boxed-btn3-white">Send</a>
                        {% else %}
                            <br>
                        {% endif %}
                    </div>
                </div>
                <div class="col-xl-4 col-md-4">
                    <div class="single_service">
                        <div class="icon">
                            <i class="flaticon-money-2"></i>
                        </div>
                        <h3>Request</h3>
                        <p>Request money from your friend without hesitation.</p>
                        {% if perms.app.add_transaction %}
                            <a href="{% url 'login_attempt' %}" class="boxed-btn3-white">Request</a>
                        {% else %}
                            <br>
                        {% endif %}
                    </div>
                </div>
                <div class="col-xl-4 col-md-4">
                    <div class="single_service">
                        <div class="icon">
                            <i class="flaticon-bank"></i>
                        </div>
                        <h3>Transfer</h3>
                        <p>Transfer money to bank with only one click.</p>
                        {% if perms.app.change_account %}
                            <a href="{% url 'login_attempt' %}" class="boxed-btn3-white">Transfer</a>
                        {% else %}
                            <br>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- service_area_end -->


    <!-- footer start -->
    <footer class="footer">
        <div class="copy-right_text">
            <div class="container">
                <div class="footer_border"></div>
                    <div class="row">
                        <div class="col-xl-12">
                            <p class="copy_right text-center">
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">NANDAO777</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            </p>
                        </div>
                    </div>
                </div>
            </div>
    </footer>
<!-- footer end  -->

    <!-- link that opens popup -->

    <!-- JS here -->
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js'%}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'js/ajax-form.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'js/scrollIt.js' %}"></script>
    <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/nice-select.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/gijgo.min.js' %}"></script>
    <!--contact js-->
    <script src="{% static 'js/contact.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.form.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>

    <script src="{% static 'js/main.js' %}"></script>
    <script>
        $('#datepicker').datepicker({
            iconsLibrary: 'fontawesome',
            icons: {
                rightIcon: '<span class="fa fa-caret-down"></span>'
            }
        });
        $('#datepicker2').datepicker({
            iconsLibrary: 'fontawesome',
            icons: {
                rightIcon: '<span class="fa fa-caret-down"></span>'
            }

        });
    $(document).ready(function() {
    $('.js-example-basic-multiple').select2();
});
    </script>
</body>

</html>

Paradise/users/templates/logout.html
{% extends "base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Sign Out" %}
{% endblock head_title %}
{% block content %}
    <h1>{% trans "Sign Out" %}</h1>
    <p>{% trans "Are you sure you want to sign out?" %}</p>
    <form method="post" action="{% url 'logout' %}">
        {% csrf_token %}
        <button type="submit">{% trans 'Logout' %}</button>
    </form>
{% endblock content %}

Paradise/users/templates/success.html
{% extends "base.html" %}

{% block title %}Success{% endblock title %}

{% block content %}
    <h2>Success!</h2>
    <p>Your action was successful. You can now <a href="{% url 'login_attempt' %}">login</a>.</p>
{% endblock content %}

Paradise/users/templates/token_send.html
{% extends "base.html" %}

{% block title %}Verify Your Email{% endblock title %}

{% block content %}
    <h2>Check Your Email</h2>
    <p>We have sent you an email to verify your account. Please check your inbox and click the verification link.</p>
{% endblock content %}